
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DECR_TOKEN INCR_TOKEN IOARG_TOKEN IOCMD_TOKEN MATH_TOKEN MEMORY_CMD_TOKEN MEMORY_LOC_TOKEN MEMORY_SET_TOKEN NUMBER_TOKEN\n    program : MEMORY_SET_TOKEN NUMBER_TOKEN\n            | IOCMD_TOKEN IOARG_TOKEN\n            | MATH_TOKEN NUMBER_TOKEN\n            | MEMORY_CMD_TOKEN MEMORY_LOC_TOKEN\n    \n    io : IOCMD_TOKEN IOARG_TOKEN\n    \n    set_memory : MEMORY_SET_TOKEN NUMBER_TOKEN\n    \n    math : MATH_TOKEN NUMBER_TOKEN\n    '
    
_lr_action_items = {'MEMORY_SET_TOKEN':([0,],[2,]),'IOCMD_TOKEN':([0,],[3,]),'MATH_TOKEN':([0,],[4,]),'MEMORY_CMD_TOKEN':([0,],[5,]),'$end':([1,6,7,8,9,],[0,-1,-2,-3,-4,]),'NUMBER_TOKEN':([2,4,],[6,8,]),'IOARG_TOKEN':([3,],[7,]),'MEMORY_LOC_TOKEN':([5,],[9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> MEMORY_SET_TOKEN NUMBER_TOKEN','program',2,'p_program','transpiler.py',38),
  ('program -> IOCMD_TOKEN IOARG_TOKEN','program',2,'p_program','transpiler.py',39),
  ('program -> MATH_TOKEN NUMBER_TOKEN','program',2,'p_program','transpiler.py',40),
  ('program -> MEMORY_CMD_TOKEN MEMORY_LOC_TOKEN','program',2,'p_program','transpiler.py',41),
  ('io -> IOCMD_TOKEN IOARG_TOKEN','io',2,'p_io','transpiler.py',47),
  ('set_memory -> MEMORY_SET_TOKEN NUMBER_TOKEN','set_memory',2,'p_setmemory','transpiler.py',54),
  ('math -> MATH_TOKEN NUMBER_TOKEN','math',2,'p_math','transpiler.py',60),
]
